# Generated by Django 5.1.3 on 2024-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update'),
        ),
    ]
