# Generated by Django 5.1.3 on 2024-11-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_created_article_last_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
    ]
