# Generated by Django 5.1.3 on 2024-12-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default-thumbnail.png', null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
